// Generated by https://quicktype.io

export interface PlacesResponse {
  type:        string;
  query:       string[];
  features:    Feature[];
  attribution: string;
}

export interface Feature {
  id:            string;
  type:          string;
  place_type:    string[];
  relevance:     number;
  properties:    Properties;
  text_ca:       string;
  place_name_ca: string;
  text:          string;
  place_name:    string;
  center:        number[];
  geometry:      Geometry;
  context:       Context[];
  language_ca?:  string;
  language?:     string;
}

export interface Context {
  id:           string;
  mapbox_id:    string;
  text_ca:      string;
  text:         string;
  wikidata?:    Wikidata;
  language_ca?: Language;
  language?:    Language;
  short_code?:  ShortCode;
}

export enum Language {
  CA = "ca",
}

export enum ShortCode {
  Es = "es",
  EsB = "ES-B",
}

export enum Wikidata {
  Q11492 = "Q11492",
  Q29 = "Q29",
  Q81949 = "Q81949",
}

export interface Geometry {
  coordinates: number[];
  type:        string;
}

export interface Properties {
  foursquare: string;
  landmark:   boolean;
  category:   string;
  address?:   string;
}
